
version: '3'
services:
  api-server:
    build:
      context: ./server
    ports:
      - "1000:1000"
    container_name: api-server
    stdin_open: true
    volumes:
        - ./api:/usr/src/app/server
        - /usr/src/app/server/node_modules
  react-app:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: react-app
    stdin_open: true
    volumes:
        - ./api:/usr/src/client/api
        - /usr/src/app/client/node_modules